#!/bin/bash
#
# Skript kasutajate lisamiseks failist

# Kontrolli argumentide arvu
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
    exit 1
fi

failinimi=$1

# Kontrolli, kas fail eksisteerib ja on loetav
if [ -f "$failinimi" -a -r "$failinimi" ]; then
    echo "fail on korras"
    while IFS=':' read -r kasutajanimi parool; do
        # Kontrolli, kas mõlemad väljad on olemas
        if [ -n "$kasutajanimi" ] && [ -n "$parool" ]; then
            # Lisa kasutaja ja määra parool
            ./lisa_kasutaja "$kasutajanimi"
            echo "$kasutajanimi:$parool" | chpasswd
        else
            echo "Vigane rida: $kasutajanimi"
        fi
    done < "$failinimi"
else
    echo "probleem failiga $failinimi"
    exit 1
fi
