#!/bin/bash
# Skript loob kasutaja, määrab kodukataloogi ja seab vaikimisi shelliks Bash

# Kontrollime, kas kasutajanimi on sisendina antud
if [ $# -eq 0 ]; then
    echo "Viga: kasutajanimi on puudu."
    echo "Kasutamine: $0 <kasutajanimi>"
    exit 1
fi

kasutajanimi="$1"

# Loome kasutaja, määrame kodukataloogi ja vaikimisi shelliks Bash
useradd -m -d "/home/$kasutajanimi" -s /bin/bash "$kasutajanimi"

# Kontrollime, kas kasutaja loodi edukalt
if [ $? -eq 0 ]; then
    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
    # Näitame kasutaja infot /etc/passwd failist
    grep "^$kasutajanimi:" /etc/passwd
    # Näitame kodukataloogi sisu detailselt
    echo "kokku $(du -s /home/$kasutajanimi | cut -f1)"
    ls -la "/home/$kasutajanimi"
else
    echo "Kasutaja '$kasutajanimi' loomine ebaõnnestus."
    exit 2
fi
